import * as Localization from "expo-localization";
import cache from "../utility/cache";
import i18n from "i18n-js";
i18n.translations = {
  en: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",

    Drawer: "Drawer",
    Settings: "Settings",
    Puzzle: "Puzzle",
    Similarity: "Similarity",
    Guess: "Guess",
    Distance: "Distance",
    "enter your guess (click here)": "enter your guess (click here)",
    "1st": "1st",
    "10th": "10th",
    "1000th": "1000th",
    "GREAT!": "GREAT!",
    "Day Streak": "Day Streak",
    "Word found in": "Word found in",
    guesses: "guesses",
    "Next puzzle In": "Next puzzle In",
    "You may continue exploring guesses without it affecting your score":
      "You may continue exploring guesses without it affecting your score.",
    "Share Win": "Share Win",
    "not found in our dictionary": "not found in our dictionary.",
    far: "far",
    "Next word in": "Next word in",
    "YESTERDAY'S WORD": "YESTERDAY'S WORD",
    "(click for similar words)": "(click for similar words)",
    SOLVED: "SOLVED",
    "AVG GUESSES": "AVG GUESSES",
    "🧪 STATS": "🧪 STATS",
    "Support Semantle": "Support Semantle",
    "Rate Semantle": "Rate Semantle",
    "Request Feature": "Request Feature",
    Help: "Help",
    Tutorial: "Tutorial",
    "Report Problem": "Report Problem",
    "Legacy Theme": "Legacy Theme",
    "Hide Yesterday's Word": "Hide Yesterday's Word",
    "I solved Semantle": "I solved Semantle",
    "in only one guess": "in only one guess!",
    "Download Semantle": "Download Semantle",
    in: "in",
    "guesses My first guess had a similarity of":
      "guesses. My first guess had a similarity of",
    "My first guess in the top 1000 was at guess":
      "My first guess in the top 1000 was at guess",
    "My penultimate guess had a similarity of":
      "My penultimate guess had a similarity of",
    "Language:": "Language:",
    FOUND: "FOUND",
    "Welcome to Semantle": "Welcome to Semantle",
    "The context-based word puzzle game": "The context-based word puzzle game.",
    "How to play": "How to play",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Enter a word and receive how similar it is to the daily word. Similarity is determined by context, not by spelling.",
    "Can you find the word": "Can you find the word?",
    "Play with the community": "Play with the community",
    "Playing Semantle with your friends is a great experience. You can also engage with the Reddit and Discord communities":
      "Playing Semantle with your friends is a great experience. You can also engage with the Reddit and Discord communities!",
  },
  es: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",

    Drawer: "Cajón",
    Settings: "Ajustes",
    Puzzle: "Rompecabezas",
    Similarity: "Semejanza",
    Guess: "Adivinar",
    Distance: "Distancia",
    "enter your guess (click here)": "Ingrese su conjetura (haga clic aquí)",
    "1st": "1er",
    "10th": "Décimo",
    "1000th": "1000º",
    "GREAT!": "[FIX_ME]",
    "Day Streak": "Racha de día",
    "Word found in": "Palabra encontrada en",
    guesses: "suposiciones",
    "Next puzzle In": "Siguiente rompecabezas en",
    "You may continue exploring guesses without it affecting your score":
      "Puede continuar explorando las conjeturas sin que afecte su puntaje.",
    "Share Win": "Compartir ganar",
    "not found in our dictionary": "No encontrado en nuestro diccionario.",
    far: "lejos",
    "Next word in": "Palabra siguiente en",
    "YESTERDAY'S WORD": "La palabra de ayer",
    "(click for similar words)": "(Haga clic para palabras similares)",
    SOLVED: "Resuelto",
    "AVG GUESSES": "Adivinaciones de AVG",
    "🧪 STATS": "🧪 estadísticas",
    "Support Semantle": "SEMANTE SEMANTLE",
    "Rate Semantle": "Tarifa de semantillo",
    "Request Feature": "Característica de solicitud",
    Help: "Ayudar",
    Tutorial: "Tutorial",
    "Report Problem": "Reportar problema",
    "Legacy Theme": "Tema heredado",
    "Hide Yesterday's Word": "Ocultar la palabra de ayer",
    "I solved Semantle": "Resolví semantle",
    "in only one guess": "¡En solo una conjetura!",
    "Download Semantle": "Descargar Semantle",
    in: "en",
    "guesses My first guess had a similarity of": "suposiciones.",
    "My first guess in the top 1000 was at guess":
      "Mi primera suposición en el Top 1000 estaba en Supongo",
    "My penultimate guess had a similarity of":
      "Mi penúltima suposición tuvo una similitud de",
    "Language:": "Idioma:",
    FOUND: "[FIX_ME]",
    "Welcome to Semantle": "Bienvenido a Semantle",
    "The context-based word puzzle game":
      "El juego de rompecabezas de palabras basado en contexto.",
    "How to play": "Cómo jugar",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Ingrese una palabra y reciba lo similar que es para la palabra diaria.",
    "Can you find the word": "¿Puedes encontrar la palabra?",
    "Play with the community": "Jugar con la comunidad",
  },
  sv: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",

    Drawer: "Låda",
    Settings: "inställningar",
    Puzzle: "Pussel",
    Similarity: "Likhet",
    Guess: "Gissa",
    Distance: "Distans",
    "enter your guess (click here)": "Ange ditt gissning (klicka här)",
    "1st": "1: a",
    "10th": "10: e",
    "1000th": "1000",
    "GREAT!": "BRA!",
    "Day Streak": "Dagsträva",
    "Word found in": "Ord som finns i",
    guesses: "gissningar",
    "Next puzzle In": "Nästa pussel i",
    "You may continue exploring guesses without it affecting your score":
      "Du kan fortsätta att utforska gissningar utan att det påverkar din poäng.",
    "Share Win": "Dela WIN",
    "not found in our dictionary": "hittades inte i vår ordbok.",
    far: "långt",
    "Next word in": "Nästa ord i",
    "YESTERDAY'S WORD": "Gårdagens ord",
    "(click for similar words)": "(klicka för liknande ord)",
    SOLVED: "LÖST",
    "AVG GUESSES": "Avg gissningar",
    "🧪 STATS": "🧪 Statistik",
    "Support Semantle": "Stöd Semantle",
    "Rate Semantle": "Ränta semantle",
    "Request Feature": "Begär funktion",
    Help: "Hjälp",
    Tutorial: "Handledning",
    "Report Problem": "Rapportera problem",
    "Legacy Theme": "Legacy tema",
    "Hide Yesterday's Word": "Göm gårdagens ord",
    "I solved Semantle": "Jag löste semanteln",
    "in only one guess": "i bara en gissning!",
    "Download Semantle": "Hämta Semantle",
    in: "i",
    "guesses My first guess had a similarity of": "gissningar.",
    "My first guess in the top 1000 was at guess":
      "Min första gissning i topp 1000 var på Guess",
    "My penultimate guess had a similarity of":
      "Min näst sista gissning hade en likhet av",
    "Language:": "Språk:",
    FOUND: "HITTADES",
    "Welcome to Semantle": "Välkommen till Semantle",
    "The context-based word puzzle game":
      "Det kontextbaserade ordet pusselspel.",
    "How to play": "Hur man spelar",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Ange ett ord och få hur lika det är till det dagliga ordet.",
    "Can you find the word": "Kan du hitta ordet?",
    "Play with the community": "Spela med samhället",
  },
  tr: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",

    Drawer: "Çekmece",
    Settings: "Ayarlar",
    Puzzle: "Bulmaca",
    Similarity: "Benzerlik",
    Guess: "Tahmin etmek",
    Distance: "Mesafe",
    "enter your guess (click here)": "Tahmininizi girin (buraya tıklayın)",
    "1st": "1 inci",
    "10th": "10.",
    "1000th": "1000",
    "GREAT!": "İYİ!",
    "Day Streak": "Gündüz",
    "Word found in": "Kelime bulundu",
    guesses: "tahmin etmek",
    "Next puzzle In": "Sonraki Bulma",
    "You may continue exploring guesses without it affecting your score":
      "Tahminleri puanınızı etkilemeden keşfetmeye devam edebilirsiniz.",
    "Share Win": "Paylaşmak",
    "not found in our dictionary": "Sözlüğümüzde bulunamadı.",
    far: "uzak",
    "Next word in": "Bir sonraki kelime",
    "YESTERDAY'S WORD": "Dünün Sözü",
    "(click for similar words)": "(benzer kelimeler için tıklayın)",
    SOLVED: "Çözüldü",
    "AVG GUESSES": "Avg tahmin ediyor",
    "🧪 STATS": "🧪 istatistikler",
    "Support Semantle": "Semantel Destek",
    "Rate Semantle": "Hızı semtosu",
    "Request Feature": "İstek özelliği",
    Help: "Yardım",
    Tutorial: "Öğretici",
    "Report Problem": "Sorunu bildir",
    "Legacy Theme": "Miras teması",
    "Hide Yesterday's Word": "Dünün sözcüğünü gizle",
    "I solved Semantle": "İymantayı çözdüm",
    "in only one guess": "Sadece bir tahmin!",
    "Download Semantle": "İndir semantel",
    in: "içinde",
    "guesses My first guess had a similarity of": "Tahmin eder.",
    "My first guess in the top 1000 was at guess":
      "İlk 1000'deki ilk tahminim tahmindeydi",
    "My penultimate guess had a similarity of":
      "Penültimate tahminim benzerliği vardı",
    "Language:": "Dilim:",
    FOUND: "BULUNDU",
    "Welcome to Semantle": "Semantle'ye hoş geldiniz",
    "The context-based word puzzle game": "Bağlam tabanlı kelime puzzle oyunu.",
    "How to play": "Nasıl oynanır",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Bir kelime girin ve günlük kelimenin ne kadar benzer olduğunu alınız.",
    "Can you find the word": "Kelimeyi bulabilir misin?",
  },
  de: {
    0: "0.",
    1: "1",
    2: "2",
    3: "3",
    4: "4.",
    5: "5.",
    6: "6.",
    7: "7.",
    8: "8.",
    9: "9.",
    Drawer: "Schublade",
    Settings: "Einstellungen",
    Puzzle: "Puzzle",
    Similarity: "Ähnlichkeit",
    Guess: "Erraten",
    Distance: "Distanz",
    "enter your guess (click here)":
      "Geben Sie Ihre Vermutung ein (klicken Sie hier)",
    "1st": "1",
    "10th": "10.",
    "1000th": "1000.",
    "GREAT!": "GROSSARTIG!",
    "Day Streak": "Tagesstreifen",
    "Word found in": "Wort in gefunden",
    guesses: "Vermutungen",
    "Next puzzle In": "Nächstes Rätsel in.",
    "You may continue exploring guesses without it affecting your score":
      "Sie können Vermutungen weiter erkunden, ohne Ihre Punktzahl zu beeinflussen.",
    "Share Win": "Teilen Sie den Sieg",
    "not found in our dictionary": "nicht in unserem Wörterbuch gefunden.",
    far: "weit",
    "Next word in": "Nächstes Wort in.",
    "YESTERDAY'S WORD": "Gesternes Wort",
    "(click for similar words)": "(Klicken Sie auf ähnliche Wörter)",
    SOLVED: "Gelöst",
    "AVG GUESSES": "Avg ruthes.",
    "🧪 STATS": "🧪 Statistiken",
    "Support Semantle": "Support Semantle.",
    "Rate Semantle": "Rate Semantle.",
    "Request Feature": "Anforderungsfunktion",
    Help: "Hilfe",
    Tutorial: "Lernprogramm",
    "Report Problem": "Problem melden",
    "Legacy Theme": "Legacy -Thema",
    "Hide Yesterday's Word": "Verstecken Sie das Wort von gestern",
    "I solved Semantle": "Ich habe Semantle gelöst.",
    "in only one guess": "in nur einer raten!",
    "Download Semantle": "Semantel herunterladen",
    in: "in",
    "guesses My first guess had a similarity of": "Vermutungen.",
    "My first guess in the top 1000 was at guess":
      "Meine erste Vermutung in der Top 1000 war erraten",
    "My penultimate guess had a similarity of":
      "Meine vorletzte Vermutung hatte eine Ähnlichkeit von",
    "Language:": "Sprache:",
    FOUND: "GEFUNDEN",
    "Welcome to Semantle": "Willkommen in Semantle.",
    "The context-based word puzzle game":
      "Das kontextbasierte Wort-Puzzle-Spiel.",
    "How to play": "Spielanleitung",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Geben Sie ein Wort ein und empfangen Sie, wie ähnlich das tägliche Wort ist.",
    "Can you find the word": "Kannst du das Wort finden?",
  },
  nl: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",

    Drawer: "Lade",
    Settings: "Instellingen",
    Puzzle: "Puzzel",
    Similarity: "Gelijkenis",
    Guess: "Gok",
    Distance: "Afstand",
    "enter your guess (click here)": "Voer je gok in (klik hier)",
    "1st": "1e",
    "10th": "10e",
    "1000th": "1000e",
    "GREAT!": "GROOT!",
    "Day Streak": "Dagstreep",
    "Word found in": "Woord gevonden in",
    guesses: "gissingen",
    "Next puzzle In": "Volgende puzzel in",
    "You may continue exploring guesses without it affecting your score":
      "U kunt doorgaan met het verkennen van gissingen zonder dat het uw score beïnvloedt.",
    "Share Win": "Delen Win",
    "not found in our dictionary": "niet gevonden in ons woordenboek.",
    far: "ver",
    "Next word in": "Volgend woord in",
    "YESTERDAY'S WORD": "Woord van gisteren",
    "(click for similar words)": "(Klik voor vergelijkbare woorden)",
    SOLVED: "Opgelost",
    "AVG GUESSES": "AVG gokt",
    "🧪 STATS": "🧪 statistieken",
    "Support Semantle": "Steun semantle",
    "Rate Semantle": "Tarief semantle",
    "Request Feature": "Aanvraagfunctie",
    Help: "Helpen",
    Tutorial: "Tutorial",
    "Report Problem": "Meld een probleem",
    "Legacy Theme": "Legacy Theme",
    "Hide Yesterday's Word": "Verberg het woord van gisteren",
    "I solved Semantle": "Ik heb semantel opgelost",
    "in only one guess": "in slechts één gok!",
    "Download Semantle": "Semantle downloaden",
    in: "in",
    "guesses My first guess had a similarity of": "gissingen.",
    "My first guess in the top 1000 was at guess":
      "Mijn eerste gok in de top 1000 was op gok",
    "My penultimate guess had a similarity of":
      "Mijn voorlaatste gok had een gelijkenis van",
    "Language:": "Taal:",
    FOUND: "GEVONDEN",
    "Welcome to Semantle": "Welkom bij Semantle",
    "The context-based word puzzle game":
      "Het op context gebaseerde woordpuzzelspel.",
    "How to play": "Hoe te spelen",
    "Enter a word and receive how similar it is to the daily word Similarity is determined by context not by spelling":
      "Voer een woord in en ontvang hoe vergelijkbaar het is met het dagelijkse woord.",
    "Can you find the word": "Kun je het woord vinden?",
  },
};
async function checkAndSetLocalization() {
  const language = await cache.getData("SEMANTLE::LANGUAGE", false);
  if (language) {
    i18n.locale = language;
  } else {
    i18n.locale = Localization.locale.split("-")[0];
  }
}
checkAndSetLocalization();
