import i18n from "i18n-js";
import * as Localization from "expo-localization";
i18n.translations = {
  "en": {
    "DeleteLike": "Delete this from your likes list?",
    "NoLikes": "No likes yet. Start swiping!",
    "JoinGroup": "Join Group",
    "CreateGroup": "Create Group",
    "Group": "Group",
    "Likes": "Likes",
    "GroupTopPicks": "Group Top Picks",
    "YourLikes": "Your Likes",
    "GenerateCode": "Generate Join Code",
    "GeneratingCode": "Generating Code",
    "JoinCode": "Join Code",
    "Join": "Join",
    "NoGroupPicksYetKeepSwiping": "No group picks yet. Keep swiping!",
    "GroupName": "Group Name",
    "Type": "Type",
    "Providers": "Providers",
    "Genre": "Genre",
    "Rating": "Rating",
    "Lookslikeyourlastjoincodeexpired": "Looks like your last join code expired.",
    "AudienceScore": "Audience Score",
    "MoreInfo": "More Info",
    "EnterYourScreenName": "Enter your screen name",
    "BySubmittingYouAgreeToThe": "By submitting, you agree to the",
    "TermsAndConditions": "Terms and Conditions",
    "SUBMITSCREENNAME": "SUBMIT SCREEN NAME",
    "Pleaseenterascreenname": "Please enter a screen name.",
    "WelcometoFlixPix": "Welcome to FlixPix",
    "swipeanydirectiontocontinue": "swipe any direction to continue",
    "Swiperighttovoteforashow": "Swipe right to show your interest in a film.",
    "Swipelefttovoteagainstashow": "Swipe left to vote against watching a film.",
    "Swipedowntopassonashow": "Swipe down to pass on a film.",
    "SwipeuptochooseashowasyourTopPick": "Swipe up to choose a film as your Top Pick",
    "Shakeyourphonetoundoyourlastswipe": "Try shaking your phone to undo",
    "orswipetocontinue": "(or swipe to continue.)",
    "Taponacardtogetmoreinformation": "Tap on a card to get more information.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Movie Trivia Fact: Toto was paid more than the Munchkins in The Wizard of Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "The Munchkin actors received $50 a week—which was a good wage at the time—while the dog earned $125 a week.",
    "Whatarewewatchingtonight": "What are we watching tonight?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Make or join a group, and take the hassle out of movie night.",
    "Whatareyouwaitingfor": "What are you waiting for? Swipe to get started!",
    "OtherInfo": "Other Information",
    "RankingExplaination": "Tap the heart icon to see your group's top picks, and your likes",
    "ShareExplainations": "Tap the share icon to add people to your group",
    "SwipeToContinue": "(swipe to continue)",
    "Action": "Action",
    "Adventure": "Adventure",
    "Animation": "Animation",
    "Comedy": "Comedy",
    "Crime": "Crime",
    "Documentary": "Documentary",
    "Drama": "Drama",
    "Family": "Family",
    "Fantasy": "Fantasy",
    "History": "History",
    "Horror": "Horror",
    "Music": "Music",
    "Mystery": "Mystery",
    "Romance": "Romance",
    "ScienceFiction": "Science Fiction",
    "TVMovie": "TV Movie",
    "Thriller": "Thriller",
    "War": "War",
    "Western": "Western",
    "ActionAdventure": "Action & Adventure",
    "Kids": "Kids",
    "News": "News",
    "Reality": "Reality",
    "SciFiFantasy": "Sci-Fi & Fantasy",
    "Soap": "Soap",
    "Talk": "Talk",
    "WarPolitics": "War & Politics",
    "Liked": "Liked",
    "Disliked": "Disliked",
    "Passed": "Passed",
    "TopPick": "Top Pick",
    "OK": "OK",
    "Cancel": "Cancel",
    "Undolastswipe": "Undo last swipe?",
    "Noundoisavaliable": "No undo is avaliable.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "You've swiped through all the content in your current filters!",
    "All out of top picks": "All out of top picks!",
    "Like what you see": "Like what you see?",
    "Srtvy": "Swipe right to vote for this film. We'll let you know if it's a match!",
    "Not interested": "Not interested?",
    "SLIYNIN": "Swipe left if you're not interested in this film.",
    "NOT INTERESTED": "NOT INTERESTED",
    "Is this one of your top pick": "Is this one of your top pick?",
    "MakeITCountt": "Swipe up if you really like this film and want to show it. You only have 2 per group, so make it count!",
    "PASS": "PASS",
    "Swipedowntopass": "Swiping down will pass on this film.",
    "No opinion": "No opinion?",
    "enter a group name": "⇧Enter a group name.⇧",
    "An error occured": "An error occured.",
    "No enough shows found under current filters": "No enough shows found under current filters.",
    "Invalid join code": "Invalid join code.",
    "You have already joined this group": "You have already joined this group.",
    "JCNV": "Join code not valid.",
    "Leave Group": "Leave Group?",
    "Network Error": "Network Error.",
    "Load More": "Load More",
    "Name": "Name",
    "Download the app, and join": "Download the app, and join",
    "let's find what to watch": "let's find what to watch.",
    "It'sAMatch": "IT'S A MATCH!",
    "Powered By": "Powered By",
    "This product uses the TMDb API": "This product uses the TMDb API but is not endorsed or certified by TMDb.",
    "Clear all app data": "Clear all app data?",
    "this action will delete all groups and all user data This is PERMANENT": "this action will delete all groups, and all user data. This is PERMANENT!",
    "Match Score": "Match Score"
  },
  "es": {
    "DeleteLike": "¿Eliminar esto de tu lista de Me gusta?",
    "NoLikes": "No me gusta todavía. ¡Empieza a deslizar!",
    "JoinGroup": "Unirse al grupo",
    "CreateGroup": "Crear grupo",
    "Group": "Grupo",
    "Likes": "Me gusta",
    "GroupTopPicks": "Mejores selecciones del grupo",
    "YourLikes": "Tus gustos",
    "GenerateCode": "Generar código de unión",
    "GeneratingCode": "Generando código",
    "JoinCode": "Código de unión",
    "Join": "Unirse",
    "NoGroupPicksYetKeepSwiping": "Aún no hay selecciones grupales. ¡Sigue deslizando!",
    "GroupName": "Nombre del grupo",
    "Type": "Tipo",
    "Providers": "Proveedores",
    "Genre": "Género",
    "Rating": "Calificación",
    "Lookslikeyourlastjoincodeexpired": "Parece que su último código para unirse venció.",
    "AudienceScore": "Puntuación de la audiencia",
    "MoreInfo": "Más información",
    "EnterYourScreenName": "Ingrese su nombre de usuario",
    "BySubmittingYouAgreeToThe": "Al enviar, aceptas las",
    "TermsAndConditions": "Términos y condiciones",
    "SUBMITSCREENNAME": "ENVIAR EL NOMBRE DE LA PANTALLA",
    "Pleaseenterascreenname": "Ingrese un nombre de pantalla.",
    "WelcometoFlixPix": "Bienvenido a FlixPix",
    "swipeanydirectiontocontinue": "desliza el dedo en cualquier dirección para continuar",
    "Swiperighttovoteforashow": "Desliza el dedo hacia la derecha para mostrar tu interés en una película.",
    "Swipelefttovoteagainstashow": "Desliza el dedo hacia la izquierda para votar en contra de ver una película.",
    "Swipedowntopassonashow": "Desliza el dedo hacia abajo para pasar una película.",
    "SwipeuptochooseashowasyourTopPick": "Desliza el dedo hacia arriba para elegir una película como tu mejor opción",
    "Shakeyourphonetoundoyourlastswipe": "Intenta agitar tu teléfono para deshacer",
    "orswipetocontinue": "(o desliza el dedo para continuar)",
    "Taponacardtogetmoreinformation": "Toque una tarjeta para obtener más información.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Hecho de la trivia de la película: A Toto se le pagó más que a los Munchkins en El mago de Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Los actores de Munchkin recibían $ 50 a la semana, que era un buen salario en ese momento, mientras que el perro ganaba $ 125 a la semana.",
    "Whatarewewatchingtonight": "¿Qué estamos viendo esta noche?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Forme un grupo o únase a él y elimine las molestias de la noche de cine.",
    "Whatareyouwaitingfor": "¿Que estas esperando? ¡Desliza para comenzar!",
    "OtherInfo": "Otra información",
    "RankingExplaination": "Toca el ícono del corazón para ver las opciones principales de tu grupo y tus Me gusta",
    "ShareExplainations": "Toca el ícono de compartir para agregar personas a tu grupo",
    "SwipeToContinue": "(desliza para continuar)",
    "Action": "Acción",
    "Adventure": "Aventura",
    "Animation": "Animación",
    "Comedy": "Comedia",
    "Crime": "Crimen",
    "Documentary": "Documental",
    "Drama": "Drama",
    "Family": "Familia",
    "Fantasy": "Fantasía",
    "History": "Historia",
    "Horror": "Horror",
    "Music": "Música",
    "Mystery": "Misterio",
    "Romance": "Romance",
    "ScienceFiction": "Ciencia ficción",
    "TVMovie": "Película de televisión",
    "Thriller": "Thriller",
    "War": "Guerra",
    "Western": "Occidental",
    "ActionAdventure": "Acción y aventura",
    "Kids": "Niños",
    "News": "Noticias",
    "Reality": "Realidad",
    "SciFiFantasy": "Ciencia ficción y fantasía",
    "Soap": "Jabón",
    "Talk": "Hablar",
    "WarPolitics": "Guerra y política",
    "Liked": "Me gustó",
    "Disliked": "No me gustó",
    "Passed": "Aprobado",
    "TopPick": "Top Pick",
    "OK": "OK",
    "Cancel": "Cancelar",
    "Undolastswipe": "¿Deshacer el último deslizamiento?",
    "Noundoisavaliable": "No hay deshacer disponible.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "¡Has pasado por todo el contenido de tus filtros actuales!",
    "All out of top picks": "¡Todos fuera de las mejores selecciones!",
    "Like what you see": "¿Te gusta lo que ves?",
    "Srtvy": "Desliza el dedo hacia la derecha para votar por esta película. ¡Te avisaremos si coincide!",
    "Not interested": "¿No interesado?",
    "SLIYNIN": "Desliza el dedo hacia la izquierda si no estás interesado en esta película.",
    "NOT INTERESTED": "NO INTERESADO",
    "Is this one of your top pick": "¿Es esta una de tus mejores opciones?",
    "MakeITCountt": "Desliza hacia arriba si realmente te gusta esta película y quieres mostrarla. Solo tienes 2 por grupo, ¡así que haz que cuente!",
    "PASS": "APROBADO",
    "Swipedowntopass": "Deslizar hacia abajo pasará esta película.",
    "No opinion": "¿Sin opinión?",
    "enter a group name": "⇧Introduzca un nombre de grupo.⇧",
    "An error occured": "Ocurrió un error.",
    "No enough shows found under current filters": "No se encontraron suficientes programas en los filtros actuales.",
    "Invalid join code": "Código de unión no válido.",
    "You have already joined this group": "Ya te has unido a este grupo.",
    "JCNV": "El código de unión no es válido.",
    "Leave Group": "¿Salir del grupo?",
    "Network Error": "Error de red.",
    "Load More": "Cargar más",
    "Name": "Nombre",
    "Download the app, and join": "Descarga la aplicación y únete",
    "let's find what to watch": "encontremos qué mirar.",
    "It'sAMatch": "¡ES UN PARTIDO!",
    "Powered By": "Desarrollado por",
    "This product uses the TMDb API": "Este producto utiliza la API de TMDb pero no está respaldado ni certificado por TMDb.",
    "Clear all app data": "¿Borrar todos los datos de la aplicación?",
    "this action will delete all groups and all user data This is PERMANENT": "esta acción eliminará todos los grupos y todos los datos del usuario. ¡Esto es PERMANENTE!",
    "Match Score": "Puntuación del partido"
  },
  "ru": {
    "DeleteLike": "Удалить это из списка лайков?",
    "NoLikes": "Пока нет лайков. Начни смахивать!",
    "JoinGroup": "Присоединиться к группе",
    "CreateGroup": "Создать группу",
    "Group": "Группа",
    "Likes": "Нравится",
    "GroupTopPicks": "Лучшие предложения группы",
    "YourLikes": "Ваши лайки",
    "GenerateCode": "Создать код присоединения",
    "GeneratingCode": "Генерация кода",
    "JoinCode": "Код регистрации",
    "Join": "Присоединяйтесь",
    "NoGroupPicksYetKeepSwiping": "Групповых выборов пока нет. Продолжайте листать!",
    "GroupName": "Название группы",
    "Type": "Тип",
    "Providers": "Провайдеры",
    "Genre": "Жанр",
    "Rating": "Рейтинг",
    "Lookslikeyourlastjoincodeexpired": "Похоже, срок действия вашего последнего кода присоединения истек.",
    "AudienceScore": "Оценка аудитории",
    "MoreInfo": "Подробнее",
    "EnterYourScreenName": "Введите свой псевдоним",
    "BySubmittingYouAgreeToThe": "Отправляя, вы соглашаетесь с",
    "TermsAndConditions": "Положения и условия",
    "SUBMITSCREENNAME": "ОТПРАВИТЬ НАЗВАНИЕ ЭКРАНА",
    "Pleaseenterascreenname": "Пожалуйста, введите псевдоним.",
    "WelcometoFlixPix": "Добро пожаловать в FlixPix",
    "swipeanydirectiontocontinue": "проведите пальцем в любом направлении, чтобы продолжить",
    "Swiperighttovoteforashow": "Проведите пальцем вправо, чтобы показать свой интерес к фильму.",
    "Swipelefttovoteagainstashow": "Проведите пальцем влево, чтобы проголосовать против просмотра фильма.",
    "Swipedowntopassonashow": "Проведите вниз, чтобы перейти к фильму.",
    "SwipeuptochooseashowasyourTopPick": "Проведите пальцем вверх, чтобы выбрать фильм в качестве лучшего выбора",
    "Shakeyourphonetoundoyourlastswipe": "Попробуйте встряхнуть телефон, чтобы отменить действие",
    "orswipetocontinue": "(или проведите пальцем, чтобы продолжить.)",
    "Taponacardtogetmoreinformation": "Нажмите на карточку, чтобы получить дополнительную информацию.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Факты о фильмах: Тото платили больше, чем Жевунам в «Волшебнике страны Оз»",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Актеры манчкинов получали 50 долларов в неделю - что было неплохим заработком в то время, - в то время как собака зарабатывала 125 долларов в неделю.",
    "Whatarewewatchingtonight": "Что мы смотрим сегодня вечером?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Создайте группу или присоединитесь к ней и избавьтесь от хлопот во время просмотра фильмов.",
    "Whatareyouwaitingfor": "Чего ты ждешь? Проведите пальцем по экрану, чтобы начать!",
    "OtherInfo": "Другая информация",
    "RankingExplaination": "Коснитесь значка сердца, чтобы увидеть лучшие выборы вашей группы и ваши лайки",
    "ShareExplainations": "Нажмите значок «Поделиться», чтобы добавить людей в свою группу",
    "SwipeToContinue": "(проведите пальцем, чтобы продолжить)",
    "Action": "Действие",
    "Adventure": "Приключение",
    "Animation": "Анимация",
    "Comedy": "Комедия",
    "Crime": "Преступление",
    "Documentary": "Документальный фильм",
    "Drama": "Драма",
    "Family": "Семья",
    "Fantasy": "Фантазия",
    "History": "История",
    "Horror": "Ужас",
    "Music": "Музыка",
    "Mystery": "Тайна",
    "Romance": "Романтика",
    "ScienceFiction": "Научная фантастика",
    "TVMovie": "ТВ-фильм",
    "Thriller": "Триллер",
    "War": "Война",
    "Western": "Западный",
    "ActionAdventure": "Боевики и приключения",
    "Kids": "Дети",
    "News": "Новости",
    "Reality": "Реальность",
    "SciFiFantasy": "Научная фантастика и фэнтези",
    "Soap": "Мыло",
    "Talk": "Обсуждение",
    "WarPolitics": "Война и политика",
    "Liked": "Понравилось",
    "Disliked": "Не понравилось",
    "Passed": "Прошло",
    "TopPick": "Лучший выбор",
    "OK": "ОК",
    "Cancel": "Отменить",
    "Undolastswipe": "Отменить последнее смахивание?",
    "Noundoisavaliable": "Отменить нельзя.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Вы просмотрели весь контент в ваших текущих фильтрах!",
    "All out of top picks": "Все из лучших!",
    "Like what you see": "Нравится то, что вы видите?",
    "Srtvy": "Проведите по экрану вправо, чтобы проголосовать за этот фильм. Мы сообщим вам, если это совпадение!",
    "Not interested": "Не интересует?",
    "SLIYNIN": "Проведите пальцем влево, если этот фильм вас не интересует.",
    "NOT INTERESTED": "НЕ ИНТЕРЕСНО",
    "Is this one of your top pick": "Это один из ваших лучших выборов?",
    "MakeITCountt": "Смахните вверх, если вам действительно нравится этот фильм и вы хотите его показать. У вас есть только 2 на группу, так что учитывайте!",
    "PASS": "ПРОЙТИ",
    "Swipedowntopass": "Проведите пальцем вниз по этому фильму.",
    "No opinion": "Нет мнения?",
    "enter a group name": "⇧Введите название группы.",
    "An error occured": "Произошла ошибка.",
    "No enough shows found under current filters": "Под текущими фильтрами не найдено достаточно шоу.",
    "Invalid join code": "Недействительный код присоединения.",
    "You have already joined this group": "Вы уже присоединились к этой группе.",
    "JCNV": "Код присоединения недействителен.",
    "Leave Group": "Покинуть группу?",
    "Network Error": "Ошибка сети.",
    "Load More": "Загрузить еще",
    "Name": "Имя",
    "Download the app, and join": "Загрузите приложение и присоединяйтесь",
    "let's find what to watch": "давай найдем, что смотреть.",
    "It'sAMatch": "ЭТО МАТЧ!",
    "Powered By": "При поддержке",
    "This product uses the TMDb API": "Этот продукт использует API TMDb, но не одобрен и не сертифицирован TMDb.",
    "Clear all app data": "Очистить все данные приложения?",
    "this action will delete all groups and all user data This is PERMANENT": "это действие удалит все группы и все пользовательские данные. Это ПОСТОЯННО!",
    "Match Score": "Счет матча"
  },
  "ja": {
    "DeleteLike": "いいねリストから削除しますか？ ||いいねはまだありません。スワイプ開始！ ||グループに参加 ||グループを作成 ||グループ ||いいね ||グループのトップピック ||あなたのいいね ||結合コードを生成 ||コードの生成 ||参加コード ||参加 ||グループの選択はまだありません。スワイプし続ける！ ||グループ名",
    "NoLikes": "|| と入力プロバイダー ||ジャンル ||評価 ||最後の参加コードの有効期限が切れたようです。 ||オーディエンス スコア ||詳細 ||スクリーンネームを入力してください ||送信することにより、",
    "JoinGroup": "に同意したことになります。利用規約 ||送信画面名 ||スクリーンネームを入力してください。",
    "CreateGroup": "FlixPix へようこそ ||続行するには任意の方向にスワイプ ||右にスワイプして、映画への関心を示します。 ||左にスワイプして、映画の視聴に反対票を投じます。 ||下にスワイプしてフィルムを渡します。 ||上にスワイプして、トップ ピックとして映画を選択します ||携帯電話を振って取り消してみてください",
    "Group": "(またはスワイプして続行します。) ||カードをタップすると、詳細情報が表示されます。 ||映画のトリビアの事実: オズの魔法使いでは、トトはマンチキンよりも多く支払われました ||マンチキンの俳優たちは週に 50 ドルを受け取っていましたが、これは当時としては高水準でしたが、犬は週に 125 ドルを稼ぎました。 ||今夜私たちは何を見ますか？ ||グループを作成したり、グループに参加したりして、映画の夜に煩わされないようにしましょう。 ||あなたは何を待っていますか？スワイプして始めましょう！ ||その他の情報 ||ハートのアイコンをタップして、グループのトップピックとお気に入りを表示します ||共有アイコンをタップして、グループに人を追加します",
    "Likes": "(スワイプして続行) ||アクション ||冒険 ||アニメーション ||コメディ ||犯罪 ||ドキュメンタリー ||ドラマ ||家族 ||ファンタジー ||歴史 ||ホラー ||音楽 ||ミステリー ||ロマンス ||サイエンス フィクション ||テレビ映画 ||スリラー ||戦争 ||西洋 ||アクション &amp; アドベンチャー ||キッズ ||ニュース ||現実",
    "GroupTopPicks": "SF &amp; ファンタジー ||石鹸 ||トーク ||戦争と政治 ||いいね ||嫌い ||合格 ||トップピック",
    "YourLikes": "OK ||キャンセル ||最後のスワイプを元に戻しますか? ||元に戻すことはできません。 ||現在のフィルターのすべてのコンテンツをスワイプしました。 ||すべてのトップピックから！ ||あなたが見るもののように？ ||この映画に投票するには、右にスワイプしてください。マッチングしたらお知らせします！ ||興味がない？ ||この映画に興味がない場合は、左にスワイプしてください。 ||興味がない ||これはあなたのトップピックの1つですか？ ||この映画が本当に気に入って見せたい場合は、上にスワイプしてください。グループごとに 2 つしかないので、それを数えるようにしてください! ||合格 ||下にスワイプすると、このフィルムが引き継がれます。 ||異議なし？ ||一連のグループ名を入力してください。エラーが発生した。 ||現在のフィルタでは十分な番組が見つかりません。 ||無効な参加コードです。 ||あなたはすでにこのグループに参加しています。 ||参加コードが無効です。 ||グループを脱退しますか? ||ネットワークエラー。 ||もっと読み込む ||名前 ||アプリをダウンロードして参加 ||見るべきものを見つけよう。 ||それは一致です! ||によって供給 ||この製品は TMDb API を使用していますが、TMDb によって承認または認定されていません。 ||アプリのデータをすべて消去しますか? ||このアクションにより、すべてのグループとすべてのユーザー データが削除されます。これは永久です！ ||マッチスコア"
  },
  "it": {
    "DeleteLike": "Eliminare questo dall&#39;elenco dei Mi piace?",
    "NoLikes": "Nessun mi piace ancora. Inizia a scorrere!",
    "JoinGroup": "Unisciti al gruppo",
    "CreateGroup": "Crea gruppo",
    "Group": "Gruppo",
    "Likes": "Mi piace",
    "GroupTopPicks": "Le migliori scelte del gruppo",
    "YourLikes": "I tuoi Mi piace",
    "GenerateCode": "Genera codice di iscrizione",
    "GeneratingCode": "Generazione del codice",
    "JoinCode": "Codice di iscrizione",
    "Join": "Unisciti a",
    "NoGroupPicksYetKeepSwiping": "Nessuna selezione di gruppo ancora. Continua a scorrere!",
    "GroupName": "Nome del gruppo",
    "Type": "Digita",
    "Providers": "Fornitori",
    "Genre": "Genere",
    "Rating": "Valutazione",
    "Lookslikeyourlastjoincodeexpired": "Sembra che il tuo ultimo codice di iscrizione sia scaduto.",
    "AudienceScore": "Punteggio del pubblico",
    "MoreInfo": "Maggiori informazioni",
    "EnterYourScreenName": "Inserisci il tuo pseudonimo",
    "BySubmittingYouAgreeToThe": "Inviando, accetti i",
    "TermsAndConditions": "Termini e condizioni",
    "SUBMITSCREENNAME": "INVIA NOME SCHERMATA",
    "Pleaseenterascreenname": "Inserisci un nome utente.",
    "WelcometoFlixPix": "Benvenuto in FlixPix",
    "swipeanydirectiontocontinue": "scorri in qualsiasi direzione per continuare",
    "Swiperighttovoteforashow": "Scorri verso destra per mostrare il tuo interesse per un film.",
    "Swipelefttovoteagainstashow": "Scorri verso sinistra per votare contro la visione di un film.",
    "Swipedowntopassonashow": "Scorri verso il basso per passare un film.",
    "SwipeuptochooseashowasyourTopPick": "Scorri verso l&#39;alto per scegliere un film come scelta migliore",
    "Shakeyourphonetoundoyourlastswipe": "Prova a scuotere il telefono per annullare",
    "orswipetocontinue": "(o scorri per continuare.)",
    "Taponacardtogetmoreinformation": "Tocca una carta per ottenere maggiori informazioni.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Curiosità sul film: Toto è stato pagato più dei Munchkin ne Il mago di Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Gli attori di Munchkin ricevevano $ 50 a settimana, che all&#39;epoca era un buon salario, mentre il cane guadagnava $ 125 a settimana.",
    "Whatarewewatchingtonight": "Cosa guardiamo stasera?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Crea o unisciti a un gruppo e elimina il fastidio della serata al cinema.",
    "Whatareyouwaitingfor": "Che cosa state aspettando? Scorri per iniziare!",
    "OtherInfo": "Altre informazioni",
    "RankingExplaination": "Tocca l&#39;icona del cuore per vedere le scelte migliori del tuo gruppo e i tuoi Mi piace",
    "ShareExplainations": "Tocca l&#39;icona di condivisione per aggiungere persone al tuo gruppo",
    "SwipeToContinue": "(scorri per continuare)",
    "Action": "Azione",
    "Adventure": "Avventura",
    "Animation": "Animazione",
    "Comedy": "Commedia",
    "Crime": "Crimine",
    "Documentary": "Documentario",
    "Drama": "Drammatico",
    "Family": "Famiglia",
    "Fantasy": "Fantasia",
    "History": "Storia",
    "Horror": "Orrore",
    "Music": "Musica",
    "Mystery": "Mistero",
    "Romance": "Romantico",
    "ScienceFiction": "Fantascienza",
    "TVMovie": "Film per la TV",
    "Thriller": "Thriller",
    "War": "Guerra",
    "Western": "occidentale",
    "ActionAdventure": "Azione e avventura",
    "Kids": "Bambini",
    "News": "Notizie",
    "Reality": "Realtà",
    "SciFiFantasy": "Fantascienza e fantasy",
    "Soap": "Sapone",
    "Talk": "Parla",
    "WarPolitics": "Guerra e politica",
    "Liked": "Mi è piaciuto",
    "Disliked": "Non mi è piaciuto",
    "Passed": "Superato",
    "TopPick": "Scelta migliore",
    "OK": "OK",
    "Cancel": "Annulla",
    "Undolastswipe": "Annullare l&#39;ultimo passaggio?",
    "Noundoisavaliable": "Nessun annullamento è disponibile.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Hai fatto scorrere tutto il contenuto nei tuoi filtri attuali!",
    "All out of top picks": "Tutto fuori dalle scelte migliori!",
    "Like what you see": "Ti piace quello che vedi?",
    "Srtvy": "Scorri verso destra per votare questo film. Ti faremo sapere se corrisponde!",
    "Not interested": "Non interessato?",
    "SLIYNIN": "Scorri verso sinistra se non sei interessato a questo film.",
    "NOT INTERESTED": "NON INTERESSATO",
    "Is this one of your top pick": "Questa è una delle tue scelte migliori?",
    "MakeITCountt": "Scorri verso l&#39;alto se ti piace davvero questo film e vuoi mostrarlo. Ne hai solo 2 per gruppo, quindi fallo contare!",
    "PASS": "PASS",
    "Swipedowntopass": "Scorri verso il basso passerà su questo film.",
    "No opinion": "Nessuna opinione?",
    "enter a group name": "⇧Inserisci il nome di un gruppo.⇧",
    "An error occured": "Si è verificato un errore.",
    "No enough shows found under current filters": "Nessun numero sufficiente di spettacoli trovati con i filtri attuali.",
    "Invalid join code": "Codice di partecipazione non valido.",
    "You have already joined this group": "Ti sei già iscritto a questo gruppo.",
    "JCNV": "Codice di iscrizione non valido.",
    "Leave Group": "Lascia il gruppo?",
    "Network Error": "Errore di rete.",
    "Load More": "Carica altro",
    "Name": "Nome",
    "Download the app, and join": "Scarica l&#39;app e unisciti a",
    "let's find what to watch": "scopriamo cosa guardare.",
    "It'sAMatch": "È UNA PARTITA!",
    "Powered By": "Realizzato da",
    "This product uses the TMDb API": "Questo prodotto utilizza l&#39;API TMDb ma non è approvato o certificato da TMDb.",
    "Clear all app data": "Cancellare tutti i dati dell&#39;app?",
    "this action will delete all groups and all user data This is PERMANENT": "questa azione eliminerà tutti i gruppi e tutti i dati utente. Questo è PERMANENTE!",
    "Match Score": "Punteggio partita Match"
  },
  "fr": {
    "DeleteLike": "Supprimer ceci de votre liste de likes ?",
    "NoLikes": "Pas encore de like. Commencez à glisser !",
    "JoinGroup": "Rejoindre le groupe",
    "CreateGroup": "Créer un groupe",
    "Group": "Groupe",
    "Likes": "J&#39;aime",
    "GroupTopPicks": "Meilleurs choix du groupe",
    "YourLikes": "Vos goûts",
    "GenerateCode": "Générer le code de jointure",
    "GeneratingCode": "Génération de code",
    "JoinCode": "Rejoindre le code",
    "Join": "Rejoindre",
    "NoGroupPicksYetKeepSwiping": "Aucun choix de groupe pour le moment. Continuez à glisser !",
    "GroupName": "Nom du groupe",
    "Type": "Tapez",
    "Providers": "Fournisseurs",
    "Genre": "Genre",
    "Rating": "Évaluation",
    "Lookslikeyourlastjoincodeexpired": "On dirait que votre dernier code de connexion a expiré.",
    "AudienceScore": "Score d&#39;audience",
    "MoreInfo": "Plus d&#39;informations",
    "EnterYourScreenName": "Entrez votre pseudo",
    "BySubmittingYouAgreeToThe": "En soumettant, vous acceptez les",
    "TermsAndConditions": "Termes et conditions",
    "SUBMITSCREENNAME": "ENVOYER LE NOM DE L&#39;ÉCRAN",
    "Pleaseenterascreenname": "Veuillez saisir un nom d&#39;écran.",
    "WelcometoFlixPix": "Bienvenue sur FlixPix",
    "swipeanydirectiontocontinue": "balayez n&#39;importe quelle direction pour continuer",
    "Swiperighttovoteforashow": "Balayez vers la droite pour montrer votre intérêt pour un film.",
    "Swipelefttovoteagainstashow": "Balayez vers la gauche pour voter contre le visionnage d&#39;un film.",
    "Swipedowntopassonashow": "Balayez vers le bas pour passer un film.",
    "SwipeuptochooseashowasyourTopPick": "Balayez vers le haut pour choisir un film comme premier choix",
    "Shakeyourphonetoundoyourlastswipe": "Essayez de secouer votre téléphone pour annuler",
    "orswipetocontinue": "(ou glissez pour continuer.)",
    "Taponacardtogetmoreinformation": "Appuyez sur une carte pour obtenir plus d&#39;informations.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Film Trivia Fact: Toto a été payé plus que les Munchkins dans Le Magicien d&#39;Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Les acteurs de Munchkin recevaient 50 $ par semaine, ce qui était un bon salaire à l&#39;époque, tandis que le chien gagnait 125 $ par semaine.",
    "Whatarewewatchingtonight": "Qu&#39;est-ce qu&#39;on regarde ce soir ?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Créez ou rejoignez un groupe et simplifiez-vous les soirées cinéma.",
    "Whatareyouwaitingfor": "Qu&#39;est-ce que tu attends? Faites glisser pour commencer !",
    "OtherInfo": "Autres informations",
    "RankingExplaination": "Appuyez sur l&#39;icône en forme de cœur pour voir les meilleurs choix de votre groupe et vos goûts",
    "ShareExplainations": "Appuyez sur l&#39;icône de partage pour ajouter des personnes à votre groupe",
    "SwipeToContinue": "(glissez pour continuer)",
    "Action": "Action",
    "Adventure": "Aventure",
    "Animation": "Animations",
    "Comedy": "Comédie",
    "Crime": "Criminalité",
    "Documentary": "Documentaire",
    "Drama": "Drame",
    "Family": "Famille",
    "Fantasy": "Fantaisie",
    "History": "Histoire",
    "Horror": "Horreur",
    "Music": "Musique",
    "Mystery": "Mystère",
    "Romance": "Romantique",
    "ScienceFiction": "Science-Fiction",
    "TVMovie": "Téléfilm",
    "Thriller": "Thriller",
    "War": "Guerre",
    "Western": "Ouest",
    "ActionAdventure": "Action &amp; Aventure",
    "Kids": "Enfants",
    "News": "Nouvelles",
    "Reality": "Réalité",
    "SciFiFantasy": "Science-fiction et fantastique",
    "Soap": "Savon",
    "Talk": "Parler",
    "WarPolitics": "Guerre et politique",
    "Liked": "J&#39;ai aimé",
    "Disliked": "Je n&#39;ai pas aimé",
    "Passed": "Passé",
    "TopPick": "Meilleur choix",
    "OK": "D&#39;accord",
    "Cancel": "Annuler",
    "Undolastswipe": "Annuler le dernier balayage ?",
    "Noundoisavaliable": "Aucune annulation n&#39;est disponible.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Vous avez parcouru tout le contenu de vos filtres actuels !",
    "All out of top picks": "Tous parmi les meilleurs choix !",
    "Like what you see": "Aimez ce que vous voyez?",
    "Srtvy": "Balayez vers la droite pour voter pour ce film. Nous vous dirons si c&#39;est un match!",
    "Not interested": "Pas intéressé?",
    "SLIYNIN": "Balayez vers la gauche si vous n&#39;êtes pas intéressé par ce film.",
    "NOT INTERESTED": "PAS INTÉRESSÉ",
    "Is this one of your top pick": "Est-ce l&#39;un de vos meilleurs choix ?",
    "MakeITCountt": "Balayez vers le haut si vous aimez vraiment ce film et que vous voulez le montrer. Vous n&#39;en avez que 2 par groupe, alors faites en sorte que ça compte !",
    "PASS": "PASS",
    "Swipedowntopass": "Glisser vers le bas transmettra ce film.",
    "No opinion": "Pas d&#39;opinion?",
    "enter a group name": "⇧Entrez un nom de groupe.⇧",
    "An error occured": "Une erreur s&#39;est produite.",
    "No enough shows found under current filters": "Pas assez d&#39;émissions trouvées sous les filtres actuels.",
    "Invalid join code": "Code de connexion invalide.",
    "You have already joined this group": "Vous avez déjà rejoint ce groupe.",
    "JCNV": "Code d&#39;adhésion non valide.",
    "Leave Group": "Quitter le groupe?",
    "Network Error": "Erreur de réseau.",
    "Load More": "Charger plus",
    "Name": "Nom",
    "Download the app, and join": "Téléchargez l&#39;application et rejoignez",
    "let's find what to watch": "trouvons quoi regarder.",
    "It'sAMatch": "C&#39;EST UN MATCH !",
    "Powered By": "Propulsé par",
    "This product uses the TMDb API": "Ce produit utilise l&#39;API TMDb mais n&#39;est ni approuvé ni certifié par TMDb.",
    "Clear all app data": "Effacer toutes les données de l&#39;application ?",
    "this action will delete all groups and all user data This is PERMANENT": "cette action supprimera tous les groupes et toutes les données utilisateur. C&#39;est PERMANENT !",
    "Match Score": "Score du match"
  },
  "ar": {
    "DeleteLike": "حذف هذا من قائمة الإعجابات الخاصة بك؟",
    "NoLikes": "لا يحب حتى الآن. ابدأ الضرب!",
    "JoinGroup": "إنضم إلى المجموعة",
    "CreateGroup": "إنشاء مجموعة",
    "Group": "المجموعة",
    "Likes": "الإعجابات",
    "GroupTopPicks": "أفضل المجموعات",
    "YourLikes": "الإعجابات الخاصة بك",
    "GenerateCode": "إنشاء رمز الانضمام",
    "GeneratingCode": "توليد كود",
    "JoinCode": "الانضمام إلى Code",
    "Join": "انضمام",
    "NoGroupPicksYetKeepSwiping": "لا مجموعة يختار بعد. استمر في الضرب!",
    "GroupName": "اسم المجموعة",
    "Type": "اكتب",
    "Providers": "الموفرون",
    "Genre": "النوع",
    "Rating": "التقييم",
    "Lookslikeyourlastjoincodeexpired": "يبدو أن رمز الانضمام الأخير الخاص بك قد انتهت صلاحيته.",
    "AudienceScore": "نقاط الجمهور",
    "MoreInfo": "مزيد من المعلومات",
    "EnterYourScreenName": "أدخل اسم شاشتك",
    "BySubmittingYouAgreeToThe": "من خلال الإرسال ، فإنك توافق على",
    "TermsAndConditions": "الشروط والأحكام",
    "SUBMITSCREENNAME": "إرسال اسم الشاشة",
    "Pleaseenterascreenname": "الرجاء إدخال اسم الشاشة.",
    "WelcometoFlixPix": "مرحبًا بك في FlixPix",
    "swipeanydirectiontocontinue": "انتقد أي اتجاه للمتابعة",
    "Swiperighttovoteforashow": "اسحب لليمين لإظهار اهتمامك بفيلم.",
    "Swipelefttovoteagainstashow": "اسحب لليسار للتصويت ضد مشاهدة فيلم.",
    "Swipedowntopassonashow": "اسحب لأسفل لتمرير فيلم.",
    "SwipeuptochooseashowasyourTopPick": "مرر سريعًا لاختيار فيلم باعتباره أفضل اختيار لك",
    "Shakeyourphonetoundoyourlastswipe": "حاول هز هاتفك للتراجع",
    "orswipetocontinue": "(أو اسحب للمتابعة.)",
    "Taponacardtogetmoreinformation": "اضغط على بطاقة للحصول على مزيد من المعلومات.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "حقيقة تريفيا في الفيلم: حصل توتو على أجر أكثر من مانشكينز في ساحر أوز",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "حصل ممثلو Munchkin على 50 دولارًا في الأسبوع - وهو أجر جيد في ذلك الوقت - بينما كان الكلب يكسب 125 دولارًا في الأسبوع.",
    "Whatarewewatchingtonight": "ماذا نشاهد الليلة؟",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "اصنع مجموعة أو انضم إليها ، وتخلص من المتاعب في ليلة مشاهدة الأفلام.",
    "Whatareyouwaitingfor": "ماذا تنتظر؟ انتقد لتبدأ!",
    "OtherInfo": "معلومات أخرى",
    "RankingExplaination": "اضغط على أيقونة القلب لرؤية أفضل اختيارات مجموعتك وما يعجبك",
    "ShareExplainations": "اضغط على أيقونة المشاركة لإضافة أشخاص إلى مجموعتك",
    "SwipeToContinue": "(اسحب للمتابعة)",
    "Action": "عمل",
    "Adventure": "المغامرة",
    "Animation": "الرسوم المتحركة",
    "Comedy": "كوميديا",
    "Crime": "جريمة",
    "Documentary": "وثائقي",
    "Drama": "دراما",
    "Family": "العائلة",
    "Fantasy": "الخيال",
    "History": "التاريخ",
    "Horror": "رعب",
    "Music": "موسيقى",
    "Mystery": "لغز",
    "Romance": "الرومانسية",
    "ScienceFiction": "خيال علمي",
    "TVMovie": "فيلم تلفزيوني",
    "Thriller": "إثارة",
    "War": "حرب",
    "Western": "الغربي",
    "ActionAdventure": "أكشن ومغامرة",
    "Kids": "الاطفال",
    "News": "أخبار",
    "Reality": "الواقع",
    "SciFiFantasy": "خيال علمي وفانتازيا",
    "Soap": "صابون",
    "Talk": "نقاش",
    "WarPolitics": "الحرب والسياسة",
    "Liked": "أعجبني",
    "Disliked": "لم يعجبه",
    "Passed": "ناجح",
    "TopPick": "أفضل اختيار",
    "OK": "موافق",
    "Cancel": "إلغاء",
    "Undolastswipe": "التراجع عن التمرير الأخير؟",
    "Noundoisavaliable": "لا يوجد تراجع متاح.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "لقد قمت بالتمرير عبر كل المحتوى الموجود في عوامل التصفية الحالية!",
    "All out of top picks": "كل من بين أفضل الاختيارات!",
    "Like what you see": "مثل ما ترى؟",
    "Srtvy": "انتقد الحق في التصويت لهذا الفيلم. سنخبرك إذا كانت مباراة!",
    "Not interested": "لست مهتمًا؟",
    "SLIYNIN": "اسحب لليسار إذا لم تكن مهتمًا بهذا الفيلم.",
    "NOT INTERESTED": "غير مهتم",
    "Is this one of your top pick": "هل هذا واحد من أفضل اختياراتك؟",
    "MakeITCountt": "اسحب لأعلى إذا أعجبك هذا الفيلم حقًا وترغب في عرضه. لديك 2 فقط لكل مجموعة ، لذا اجعلها مهمة!",
    "PASS": "اجتياز",
    "Swipedowntopass": "الضرب لأسفل سيمر على هذا الفيلم.",
    "No opinion": "لا رأي؟",
    "enter a group name": "⇧ أدخل اسم المجموعة.",
    "An error occured": "حدث خطأ.",
    "No enough shows found under current filters": "لم يتم العثور على عروض كافية ضمن المرشحات الحالية.",
    "Invalid join code": "رمز الانضمام غير صالح.",
    "You have already joined this group": "لقد انضممت بالفعل إلى هذه المجموعة.",
    "JCNV": "رمز الانضمام غير صالح.",
    "Leave Group": "غادر المجموعة؟",
    "Network Error": "خطأ في الشبكة.",
    "Load More": "تحميل المزيد",
    "Name": "الاسم",
    "Download the app, and join": "قم بتنزيل التطبيق وانضم إلى",
    "let's find what to watch": "دعونا نجد ما نشاهده.",
    "It'sAMatch": "انها مباراة!",
    "Powered By": "بدعم من",
    "This product uses the TMDb API": "يستخدم هذا المنتج TMDb API ولكنه غير معتمد أو معتمد من قبل TMDb.",
    "Clear all app data": "مسح جميع بيانات التطبيق؟",
    "this action will delete all groups and all user data This is PERMANENT": "سيؤدي هذا الإجراء إلى حذف جميع المجموعات وجميع بيانات المستخدم. هذا دائم!",
    "Match Score": "نتيجة المباراة"
  }
};

//   "ar": "Arabic",
//   "nl": "Dutch",
//   "en": "English",
//   "fr": "French",
//   "el": "Greek",
//   "hi": "Hindi",
//   "it": "Italian",
//   "ja": "Japanese",
//   "la": "Latin",
//   "ru": "Russian",
//   "es": "Spanish"
//de german
//sv sweetish

// sv: {
//     JoinGroup: "",
//     CreateGroup: "",
//     Group: "",
//     Likes: "",
//     GroupTopPicks: "",
//     YourLikes: "",
//     GenerateCode: "",
//     GeneratingCode: "",
//     JoinCode: "",
//   },
i18n.locale = Localization.locale;
i18n.fallbacks = true;
// {i18n.t(" ")}



